extension HighlightStyle {
  public enum Language: String, CaseIterable, Identifiable {
    case apache = "Apache"
    case applescript = "AppleScript"
    case bash = "Bash"
    case cpp = "CPP"
    case csharp = "C#"
    case css = "CSS"
    case dart = "Dart"
    case diff = "Diff"
    case django = "Django"
    case dns = "DNS"
    case dockerfile = "Dockerfile"
    case dos = "DOS"
    case excel = "Excel"
    case go = "Go"
    case http = "HTTP/HTTPS"
    case java = "Java"
    case javascript = "JavaScript"
    case json = "JSON"
    case kotlin = "Kotlin"
    case latex = "LaTeX"
    case less = "LESS"
    case makefile = "Makefile"
    case markdown = "Markdown"
    case mathematica = "Mathematica"
    case matlab = "MATLAB"
    case nginx = "Nginx"
    case objectivec = "Objective-C"
    case pgsql = "PostgreSQL"
    case php = "PHP"
    case powershell = "PowerShell"
    case properties = ".properties"
    case puppet = "Puppet"
    case python = "Python"
    case r = "R"
    case ruby = "Ruby"
    case ruleslanguage = "Oracle"
    case rust = "Rust"
    case scss = "SCSS"
    case shell = "Shell"
    case sql = "SQL"
    case swift = "Swift"
    case typescript = "TypeScript"
    case vbnet = "VB.NET"
    case xml = "XML"
    case yaml = "YAML"
    
    public var id: String {
      String(describing: self)
    }
  }
}
